# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cognitiveservicesconfig_twitterconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cognitiveservicesconfig',
            options={'verbose_name': 'Microsoft Cognitive Services Config'},
        ),
        migrations.AlterModelOptions(
            name='sentimentalscores',
            options={'verbose_name': 'Sentimental Score'},
        ),
        migrations.AlterModelOptions(
            name='twittersearchedtopics',
            options={'verbose_name': 'Twitter Searched Topic'},
        ),
        migrations.AddField(
            model_name='sentimentalscores',
            name='search',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.TwitterSearchedTopics'),
            preserve_default=False,
        ),
    ]
