# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveServicesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=32, verbose_name=b'Api Key')),
                ('language', models.CharField(default=b'es', max_length=10, verbose_name=b'Language')),
            ],
            options={
                'verbose_name': 'Microsoft Congnitive Services Config',
            },
        ),
        migrations.CreateModel(
            name='TwitterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name=b'Username')),
                ('api_key', models.CharField(max_length=255, verbose_name=b'Api Key')),
                ('access_secret', models.CharField(max_length=255, verbose_name=b'Access Secret')),
                ('consumer_key', models.CharField(max_length=255, verbose_name=b'Consumer Key')),
                ('consumer_secret', models.CharField(max_length=255, verbose_name=b'Consumer Secret')),
            ],
            options={
                'verbose_name': 'Twitter Services Config',
            },
        ),
    ]
